from typing import List

# LAYER 1: PRE-MARKET SCREENING (08:45 IST)
COILING_DMA_PROXIMITY_PCT = 0.03
COILING_RANGE_10D_MAX = 0.05
RSI_14_MIN = 35.0
RSI_14_MAX = 65.0
TURNOVER_20D_MIN_INR = 100_000_000.0

CATALYST_KEYWORDS: List[str] = [
    'L1 BIDDER', 'LOWEST BIDDER', 'CONTRACT AWARD', 'ORDER WIN',
    'OFFER FOR SALE', 'OFS', 'IPO FILING', 'STAKE SALE', 'VALUE UNLOCKING',
    'PROMOTER PURCHASE', 'CREEPING ACQUISITION', 'SAST', 'INSIDER BUY',
    'REGULATORY CLEARANCE', 'USFDA', 'EIR', 'SEBI RELIEF', 'DUTY EXEMPTION',
    'CONSORTIUM LOAN', 'REFINANCING SANCTION', 'DEBT RESTRUCTURING', 'AGR'
]

# LAYER 2: INTRADAY EXECUTION & CONFIRMATION (09:30 - 10:00 IST)
GAP_MIN_PCT = 0.002
GAP_MAX_PCT = 0.025
VOL_VELOCITY_30M_PCT = 0.25
VOL_RATIO_MIN_L2 = 1.60  # Calibrated Volume Thrust Threshold (raised from 1.30 to eliminate weak volume traps)
MIDCAP_HEADWIND_MIN_PCT = -0.005  # Benchmark Headwind Protection: Skip new long entries if Midcap index opens down <= -0.50%
UPPER_CIRCUIT_BUFFER_PCT = 0.01

# RANKING ENGINE CONFIGURATION (CRMV Engine)
USE_CRMV_RANKING = True  # Enable Composite Relative Momentum & Velocity cross-sectional ranking
CRMV_WEIGHT_VOLUME = 0.45     # Institutional volume thrust weight
CRMV_WEIGHT_RANGE_POS = 0.35  # Candle close near high persistence weight
CRMV_WEIGHT_GAP = 0.10        # Opening gap quality weight
CRMV_WEIGHT_COILING = 0.10    # Tightness to 20-DMA base coiling weight



# LAYER 3: END-OF-DAY PERSISTENCE & SWING TRANSITION (15:15 IST)
RANGE_POS_MIN_L3 = 0.70
VOL_RATIO_MIN_L3 = 2.0
ALPHA_SPREAD_MIN_L3 = 3.0

# NEGATIVE CONTROL EXCLUSION: VOLUME TRAP FILTER
VOLUME_TRAP_VOL_RATIO_MIN = 1.5
VOLUME_TRAP_RANGE_POS_MAX = 0.40

# POSITION SIZING & RISK MANAGEMENT
PORTFOLIO_INITIAL_EQUITY = 10_000_000.0
RISK_PER_TRADE_PCT = 0.01
MAX_POSITION_WEIGHT_PCT = 0.10
MAX_CONCURRENT_POSITIONS = 5
MAX_ADV_PARTICIPATION_PCT = 0.02
MAX_INITIAL_STOP_LOSS_PCT = 0.025
ATR_STOP_MULTIPLIER = 1.2

# SWING EXIT PARAMETERS
SWING_PROFIT_TAKE_GAP_PCT = 0.03
SWING_PROFIT_TAKE_INTRADAY_PCT = 0.05
SWING_MAX_HOLDING_DAYS = 5
